### ISSUE TITLE
Find a way to use the aliases inside vagrant

### ISSUE THREAD

**Issue by stocarul** [algotech/dotaliases#39]
It would be great if it is possible to use it without installing it inside the Vagrant machine.

**Comment by calina-c** [comment]
Here is an ugly workaround. Copy the `.aliases` folder to your vagrant shared folder (remember to update your local or global `.gitignore` as well). Edit `bash_aliases` (the one outside `bash/` folder, not the one inside it) and replace instances of `$HOME` with your corresponding path e.g. : `/vagrant/` or wherever you pasted the `.aliases` folder.

Source `bash_aliases` when connecting to vagrant via ssh.

Possible improvement: Having a ALIASES_HOME variable to only replace once. If that helps, I can do a PR with that.
