### ISSUE TITLE
Add aliases for loopback

### ISSUE THREAD

**Issue by stocarul** [algotech/dotaliases#54]
Please add the proposed list of commands

**Comment by paulbuda** [comment]
It would be great to have the following aliases for npm:

slb: slc loopback 

slbd : slc loopback:datasource
slbm : slc loopback:model
slbp : slc loopback:property
slba : slc loopback:acl
slbr : slc loopback:relation
slbrm : slc loopback:remote-method
slbmdlw : slc loopback:middleware 
slbbs: slc loopback:boot-script
slbead: scl loopback:export-api-def
slbs: slc loopback:swagger

**Comment by stocarul** [comment]
Use `lb` for `slc loopback`.

**Comment by stocarul** [comment]
Also use `lbmd` : slc loopback:middleware
